routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::pattern('slug', '[a-z0-9- _]+');

//Route::group([ 'namespace'=>'Admin'], function () {

# Lock screen
Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');
# All basic routes defined here
Route::get('login', 'AuthController@getSignin')->name('login');
Route::get('signin', 'AuthController@getSignin')->name('signin');
Route::post('signin', 'AuthController@postSignin')->name('postSignin');
Route::post('signup', 'AuthController@postSignup')->name('signup');
Route::post('forgot-password', 'AuthController@postForgotPassword')->name('signup');


# Forgot Password Confirmation
Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

# Logout
Route::get('logout', 'AuthController@getLogout')->name('logout');

# Account Activation
Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
//});


Route::group([ 'middleware' => 'admin'], function () {
    # GUI Crud Generator
    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('generate');
    Route::post('modelCheck', 'ModelcheckController@modelCheck');
    # Dashboard / Index
    Route::get('/', 'JoshController@showHome')->name('dashboard');
    # crop demo
    Route::post('crop_demo', 'JoshController@crop_demo')->name('crop_demo');
    # Activity log
    Route::get('activity_log', 'JoshController@ActivityLog')->name('activity_log');
    Route::get('task/data', 'TaskController@data')->name('data');
    # User Management
    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
    });
    Route::resource('users', 'UsersController');

    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

    # Group Management
    Route::group(['prefix' => 'groups'], function () {
        Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
        Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
        Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
    });
    Route::resource('groups', 'GroupsController');

    Route::get('{name?}', 'JoshController@showView');
});

# Remaining pages will be called from below controller method
# in real world scenario, you may be required to define all routes manually

Route::get('activate/{userId}/{activationCode}','FrontEndController@getActivate')->name('activate');
Route::get('forgot-password','FrontEndController@getForgotPassword')->name('forgot-password');
Route::post('forgot-password', 'FrontEndController@postForgotPassword');

# Forgot Password Confirmation
Route::post('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@postForgotPasswordConfirm');
Route::get('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@getForgotPasswordConfirm')->name('forgot-password-confirm');

resources/views/layouts/_left_menu.blade.php
<ul id="menu" class="page-sidebar-menu">
    <li {!! (Request::is('dashboard') ? 'class="active"' : '') !!}>
        <a href="{{ route('dashboard') }}">
            <i class="livicon" data-name="home" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Dashboard</span>
        </a>
    </li>

    <li {!! (Request::is('users') || Request::is('users/create') || Request::is('user_profile') || Request::is('users/*') || Request::is('deleted_users') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="user" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">Users</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('users') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('users') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Users
                </a>
            </li>
            <li {!! (Request::is('users/create') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('users/create') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Add New User
                </a>
            </li>
            <li {!! ((Request::is('users/*')) && !(Request::is('users/create')) ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::route('users.show',Sentinel::getUser()->id) }}">
                    <i class="fa fa-angle-double-right"></i>
                    View Profile
                </a>
            </li>
            <li {!! (Request::is('deleted_users') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('deleted_users') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Deleted Users
                </a>
            </li>
        </ul>
    </li>
    <li {!! (Request::is('groups') || Request::is('groups/create') || Request::is('groups/*') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="users" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Groups</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('groups') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('groups') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Group List
                </a>
            </li>
            <li {!! (Request::is('groups/create') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('groups/create') }}">
                    <i class="fa fa-angle-double-right"></i>
                    Add New Group
                </a>
            </li>
        </ul>
    </li>

    <li {!! (Request::is('blank') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('blank') }}">
            <i class="livicon" data-name="flag" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Blank Page</span>
        </a>
    </li>


</ul>

resources/views/layouts/_messages.blade.php
<li class="dropdown messages-menu ">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false"> <i class="livicon"
                                                                   data-name="message-flag"
                                                                   data-loop="true" data-color="#42aaca"
                                                                   data-hovercolor="#42aaca"
                                                                   data-size="28"></i>
        <span class="label label-success">4</span>
    </a>


    <ul class="dropdown-menu dropdown-messages mr-auto" aria-labelledby="dropdownMenuLink">
        <li class="dropdown-title">4 New Messages</li>
        <li class="unread message dropdown-item">
            <a href="javascript:;" class="message"> <i class="pull-right" data-toggle="tooltip"
                                                       data-placement="top" title="Mark as Read"><span
                            class="float-right ol livicon" data-n="adjust" data-s="10"
                            data-c="#287b0b"></span></i>
                <img src="{{ asset('assets/img/authors/avatar.jpg') }}"
                     class="img-fluid message-image" alt="icon">

                <div class="message-body">
                    <strong>Riot Zeast</strong>
                    <br>Hello, You there?
                    <br>
                    <small>8 minutes ago</small>
                </div>
            </a>
        </li>
        <li class="unread message dropdown-item">
            <a href="javascript:;" class="message">
                <i class="pull-right" data-toggle="tooltip" data-placement="top"
                   title="Mark as Read"><span class="pull-right ol livicon" data-n="adjust" data-s="10"
                                              data-c="#287b0b"></span></i>
                <img src="{{ asset('assets/img/authors/avatar1.jpg') }}"
                     class="img-fluid message-image" alt="icon">

                <div class="message-body">
                    <strong>John Kerry</strong>
                    <br>Can we Meet ?
                    <br>
                    <small>45 minutes ago</small>
                </div>
            </a>
        </li>
        <li class="unread message dropdown-item">
            <a href="javascript:;" class="message">
                <i class="float-right" data-toggle="tooltip" data-placement="top" title="Mark as Read">
                                    <span class="float-right ol livicon" data-n="adjust" data-s="10"
                                          data-c="#287b0b"></span>
                </i>
                <img src="{{ asset('assets/img/authors/avatar5.jpg') }}"
                     class="img-fluid message-image" alt="icon">

                <div class="message-body ">
                    <strong>Jenny Kerry</strong>
                    <br>Dont forgot to call...
                    <br>
                    <small>An hour ago</small>
                </div>
            </a>
        </li>
        <li class="unread message dropdown-item">
            <a href="javascript:;" class="message">
                <i class="pull-right" data-toggle="tooltip" data-placement="top" title="Mark as Read">
                                    <span class="pull-right ol livicon" data-n="adjust" data-s="10"
                                          data-c="#287b0b"></span>
                </i>
                <img src="{{ asset('assets/img/authors/avatar4.jpg') }}"
                     class="img-fluid message-image" alt="icon">

                <div class="message-body">
                    <strong>Ronny</strong>
                    <br>Hey! sup Dude?
                    <br>
                    <small>3 Hours ago</small>
                </div>
            </a>
        </li>
        <li class="footer">
            <a href="#">View all</a>
        </li>
    </ul>
</li>

resources/views/layouts/_notifications.blade.php
<li class="dropdown notifications-menu">
    <a href="#dropdownshow" class="dropdown-toggle" data-toggle="dropdown">
        <i class="livicon" data-name="bell" data-loop="true" data-color="#e9573f"
           data-hovercolor="#e9573f" data-size="28"></i>
        <span class="label label-warning">7</span>
    </a>
    <ul class=" notifications dropdown-menu drop_notify" >
        <li class="dropdown-title">You have 7 notifications</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class=" menu remove_hovereffect">
                <li class="dropdown-item">
                    <i class="livicon danger" data-n="timer" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">after a long time</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        Just Now
                    </small>
                </li>
                <li class="dropdown-item">
                    <i class="livicon success" data-n="gift" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">Jef's Birthday today</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        Few seconds ago
                    </small>
                </li>
                <li class="dropdown-item">
                    <i class="livicon warning" data-n="dashboard" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">out of space</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        8 minutes ago
                    </small>
                </li>
                <li class="dropdown-item">
                    <i class="livicon bg-aqua" data-n="hand-right" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">New friend request</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        An hour ago
                    </small>
                </li>
                <li class="dropdown-item">
                    <i class="livicon danger" data-n="shopping-cart-in" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">On sale 2 products</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        3 Hours ago
                    </small>
                </li>
                <li class="dropdown-item">
                    <i class="livicon success" data-n="image" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">Lee Shared your photo</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        Yesterday
                    </small>
                </li>
                <li class="dropdown-item">
                    <i class="livicon warning" data-n="thumbs-up" data-s="20" data-c="white"
                       data-hc="white"></i>
                    <a href="#">David liked your photo</a>
                    <small class="pull-right">
                        <span class="livicon paddingright_10" data-n="timer" data-s="10"></span>
                        2 July 2014
                    </small>
                </li>
            </ul>
        </li>
        <li class="footer">
            <a href="#">View all</a>
        </li>
    </ul>
</li>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>
        @section('title')
            | Josh Admin Template
        @show
    </title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    {{--CSRF Token--}}
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- global css -->

    <link href="{{ asset('assets/css/app.css') }}" rel="stylesheet" type="text/css"/>
    <!-- font Awesome -->

    <!-- end of global css -->
    <!--page level css-->
    @yield('header_styles')
            <!--end of page level css-->

<body class="skin-josh">
<header class="header">
    <a href="{{ route('dashboard') }}" class="logo">
        <img src="{{ asset('assets/img/logo.png') }}" alt="logo">
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <div>
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <div class="responsive_nav"></div>
            </a>
        </div>
        <div class="navbar-right toggle">
            <ul class="nav navbar-nav  list-inline">
                @include('layouts._messages')
                @include('layouts._notifications')
                <li class=" nav-item dropdown user user-menu">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        @if(Sentinel::getUser()->pic)
                            <img src="{!! url('/').'/uploads/users/'.Sentinel::getUser()->pic !!}" alt="img" height="35px" width="35px"
                                 class="rounded-circle img-fluid float-left"/>

                        @elseif(Sentinel::getUser()->gender === "male")
                            <img src="{{ asset('assets/images/authors/avatar3.png') }}" alt="img" height="35px" width="35px"
                                 class="rounded-circle img-fluid float-left"/>

                        @elseif(Sentinel::getUser()->gender === "female")
                            <img src="{{ asset('assets/images/authors/avatar5.png') }}" alt="img" height="35px" width="35px"
                                 class="rounded-circle img-fluid float-left"/>

                        @else
                            <img src="{{ asset('assets/images/authors/no_avatar.jpg') }}" alt="img" height="35px" width="35px"
                                 class="rounded-circle img-fluid float-left"/>
                        @endif
                        <div class="riot">
                            <div>
                                <p class="user_name_max">{{ Sentinel::getUser()->first_name }} {{ Sentinel::getUser()->last_name }}</p>
                                <span>
                                        <i class="caret"></i>
                                    </span>
                            </div>
                        </div>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            @if(Sentinel::getUser()->pic)
                                <img src="{!! url('/').'/uploads/users/'.Sentinel::getUser()->pic !!}" alt="img" height="35px" width="35px"
                                     class="rounded-circle img-fluid float-left"/>

                            @elseif(Sentinel::getUser()->gender === "male")
                                <img src="{{ asset('assets/images/authors/avatar3.png') }}" alt="img" height="35px" width="35px"
                                     class="rounded-circle img-fluid float-left"/>

                            @elseif(Sentinel::getUser()->gender === "female")
                                <img src="{{ asset('assets/images/authors/avatar5.png') }}" alt="img" height="35px" width="35px"
                                     class="rounded-circle img-fluid float-left"/>
                            @else
                                <img src="{{ asset('assets/images/authors/no_avatar.jpg') }}" alt="img" height="35px" width="35px"
                                     class="rounded-circle img-fluid float-left"/>
                            @endif
                            <p class="topprofiletext">{{ Sentinel::getUser()->first_name }} {{ Sentinel::getUser()->last_name }}</p>
                        </li>
                        <!-- Menu Body -->
                        <li>
                            <a href="{{ URL::route('users.show',Sentinel::getUser()->id) }}">
                                <i class="livicon" data-name="user" data-s="18"></i>
                                My Profile
                            </a>
                        </li>
                        <li role="presentation"></li>
                        <li>
                            <a href="{{ route('users.edit', Sentinel::getUser()->id) }}">
                                <i class="livicon" data-name="gears" data-s="18"></i>
                                Account Settings
                            </a>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ URL::route('lockscreen',Sentinel::getUser()->id) }}">
                                    <i class="livicon" data-name="lock" data-size="16" data-c="#555555" data-hc="#555555" data-loop="true"></i>
                                    Lock
                                </a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ URL::to('logout') }}">
                                    <i class="livicon" data-name="sign-out" data-s="18"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

    </nav>
</header>
<div class="wrapper ">
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="left-side ">
        <section class="sidebar ">
            <div class="page-sidebar  sidebar-nav">
                <div class="nav_icons">
                    <ul class="sidebar_threeicons">
                        <li>
                            <a href="{{ URL::to('deleted_users') }}">
                                <i class="livicon" data-name="user-remove" title="Deleted users" data-loop="true"
                                   data-color="#418BCA" data-hc="#418BCA" data-s="25"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{ URL::to('dashboard') }}">
                                <i class="livicon" data-name="dashboard" title="Dashboard" data-loop="true"
                                   data-color="#e9573f" data-hc="#e9573f" data-s="25"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{ URL::to('groups') }}">
                                <i class="livicon" data-name="users" title="Groups" data-loop="true"
                                   data-color="#F89A14" data-hc="#F89A14" data-s="25"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{{ URL::to('users') }}">
                                <i class="livicon" data-name="user" title="Users" data-loop="true"
                                   data-color="#6CC66C" data-hc="#6CC66C" data-s="25"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"></div>
                <!-- BEGIN SIDEBAR MENU -->
                @include('layouts._left_menu')
                <!-- END SIDEBAR MENU -->
            </div>
        </section>
    </aside>
    <aside class="right-side">

        <!-- Notifications -->
        <div id="notific">
        @include('notifications')
        </div>

                <!-- Content -->
        @yield('content')

    </aside>
    <!-- right-side -->
</div>
<a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Return to top"
   data-toggle="tooltip" data-placement="left">
    <i class="livicon" data-name="plane-up" data-size="18" data-loop="true" data-c="#fff" data-hc="white"></i>
</a>
<!-- global js -->

<script src="{{ asset('assets/js/app.js') }}" type="text/javascript"></script>




<!-- end of global js -->
<!-- begin page level js -->
@yield('footer_scripts')
        <!-- end page level js -->
</body>
</html>

resources/views/layouts/modal_confirmation.blade.php
<div class="modal-header">
  <h4 class="modal-title" id="user_delete_confirm_title">@lang($model.'/modal.title')</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
</div>
<div class="modal-body">
    @if($error)
        <div>{!! $error !!}</div>
    @else
        @lang($model.'/modal.body')
    @endif
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">@lang($model.'/modal.cancel')</button>
  @if(!$error)
    <a href="{{ $confirm_route }}" type="button" class="btn btn-danger">@lang($model.'/modal.confirm')</a>
  @endif
</div>